### ISSUE TITLE
Bad responses from the randomuser.me API cause test failure

### ISSUE THREAD

**Issue by sfirke** [feddelegrand7/radous#1]
Hello,

I recently submitted the janitor package to CRAN and they noted that it seemed to cause new failures in radous.  After testing your package, I think the issue is that once in a while, a call to the randomuser.me API fails, displaying an error page that says "Uh oh, something bad happened".  I tried `https://randomuser.me/api/?seed=2&results=10&format=csv` and it worked 4 times, then errored the 5th.  Trying a few minutes later, it succeeded 16 times, then errored on the 17th.

Here's the sort of failure I'm seeing when I run your tests - I don't think it depends what version of janitor I'm using:
```
>   testthat::expect_identical(final,get_data(n = 10, seed = "123"))
No encoding supplied: defaulting to UTF-8.
Warning: 2 parsing failures.
row col  expected    actual         file
  2  -- 1 columns 2 columns literal data
  5  -- 1 columns 2 columns literal data

Error: `final` not identical to get_data(n = 10, seed = "123").
Names: 1 string mismatch
Attributes: < Names: 1 string mismatch >
Attributes: < Length mismatch: comparison on first 2 components >
Attributes: < Component 2: Modes: numeric, list >
Attributes: < Component 2: names for current but not for target >
Attributes: < Component 2: Attributes: < target is NULL, current is list > >
Attributes: < Component 2: target is numeric, current is tbl_df >
Length mismatch: comparison on first 1 components
Component 1: Lengths (10, 8) differ (string compare on first 8)
```

This is the same as [the failing tests on CRAN](https://cran.r-project.org/web/checks/check_results_radous.html), which I'm guessing are also caused by this issue.

To fix, maybe have your function try the API call, then if it returns this "oh no" error page, it tries again a certain number of times?  Or if there's another issue causing the API failure, like rate limit on a token you're using, address it there so it doesn't fail.

**Comment by feddelegrand7** [comment]
Hi, 

Sorry for the inconvenience, I think the `httr` package has a RETRY function. I'll implement it now, hopefully it will fix the problem. 

Best.
Fodil.

**Comment by feddelegrand7** [comment]
It's fixed. I assume I need to submit it to CRAN to fix the issue with janitor reverse dependency ?

**Comment by sfirke** [comment]
Thanks for the speedy response & fix, Fodil!  Yes I think submitting to CRAN would make sense, especially as that would fix the current check result errors for `radous` as well which I expect they'd be pleased about.

**Comment by feddelegrand7** [comment]
It's submitted :) I'll notify you as soon as I get a confirmation from the team. 

Sorry again.

**Comment by sfirke** [comment]
No problem, CRAN accepted the new janitor (I shared this issue with them) so I'm all set on my end.  I'm glad janitor's been useful to you.  Good luck with your resubmission!

**Comment by feddelegrand7** [comment]
Awesome happy that it's fixed. Very cool package btw thanks for that.
